plugins {
	id 'java-library'
}

dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

repositories {
	mavenCentral()
}

task cargoBuild(type: Exec) {
	workingDir '.'
	commandLine 'cargo', 'build', '-p', 'jni-toolbox-test'
}

test {
	dependsOn cargoBuild
	outputs.upToDateWhen { false }
	useJUnitPlatform()
	systemProperty 'java.library.path','target/debug'
}
